python nobrain_training.py -d friends --trainData s01 s02 s03 --evalData s04 --scale whatever --device "cuda:3" --ks 3 -f "conv4" -e 0 --patience 20 --lambada 0 --gamma 1e-3 --lr 1e-2 --wd 1e-3 --bs 70 --lrScheduler --decoupledWD --wandb
python nobrain_training.py -d friends --trainData s01 s02 s03 --evalData s04 --scale whatever --device "cuda:3" --ks 3 -f "conv4" -e 0 --patience 20 --lambada 0 --gamma 1e-3 --lr 1e-2 --wd 1e-3 --bs 50 --lrScheduler --decoupledWD --wandb
python nobrain_training.py -d friends --trainData s01 s02 s03 --evalData s04 --scale whatever --device "cuda:3" --ks 3 -f "conv4" -e 0 --patience 20 --lambada 0 --gamma 1e-3 --lr 1e-2 --wd 1e-3 --bs 30 --lrScheduler --decoupledWD --wandb
python nobrain_training.py -d friends --trainData s01 s02 s03 --evalData s04 --scale whatever --device "cuda:3" --ks 3 -f "conv4" -e 0 --patience 20 --lambada 0 --gamma 1e-3 --lr 1e-3 --wd 1e-3 --bs 70 --lrScheduler --decoupledWD --wandb
python nobrain_training.py -d friends --trainData s01 s02 s03 --evalData s04 --scale whatever --device "cuda:3" --ks 3 -f "conv4" -e 0 --patience 20 --lambada 0 --gamma 1e-3 --lr 1e-3 --wd 1e-3 --bs 50 --lrScheduler --decoupledWD --wandb
python nobrain_training.py -d friends --trainData s01 s02 s03 --evalData s04 --scale whatever --device "cuda:3" --ks 3 -f "conv4" -e 0 --patience 20 --lambada 0 --gamma 1e-3 --lr 1e-3 --wd 1e-3 --bs 30 --lrScheduler --decoupledWD --wandb
python nobrain_training.py -d friends --trainData s01 s02 s03 --evalData s04 --scale whatever --device "cuda:3" --ks 3 -f "conv4" -e 0 --patience 20 --lambada 0 --gamma 1e-3 --lr 1e-2 --wd 1e-3 --bs 70 --lrScheduler --decoupledWD --wandb --temperature 2
python nobrain_training.py -d friends --trainData s01 s02 s03 --evalData s04 --scale whatever --device "cuda:3" --ks 3 -f "conv4" -e 0 --patience 20 --lambada 0 --gamma 1e-3 --lr 1e-2 --wd 1e-3 --bs 50 --lrScheduler --decoupledWD --wandb --temperature 2
python nobrain_training.py -d friends --trainData s01 s02 s03 --evalData s04 --scale whatever --device "cuda:3" --ks 3 -f "conv4" -e 0 --patience 20 --lambada 0 --gamma 1e-3 --lr 1e-2 --wd 1e-3 --bs 30 --lrScheduler --decoupledWD --wandb --temperature 2
python nobrain_training.py -d friends --trainData s01 s02 s03 --evalData s04 --scale whatever --device "cuda:3" --ks 3 -f "conv4" -e 0 --patience 20 --lambada 0 --gamma 1e-3 --lr 1e-3 --wd 1e-3 --bs 70 --lrScheduler --decoupledWD --wandb --temperature 2
python nobrain_training.py -d friends --trainData s01 s02 s03 --evalData s04 --scale whatever --device "cuda:3" --ks 3 -f "conv4" -e 0 --patience 20 --lambada 0 --gamma 1e-3 --lr 1e-3 --wd 1e-3 --bs 50 --lrScheduler --decoupledWD --wandb --temperature 2
python nobrain_training.py -d friends --trainData s01 s02 s03 --evalData s04 --scale whatever --device "cuda:3" --ks 3 -f "conv4" -e 0 --patience 20 --lambada 0 --gamma 1e-3 --lr 1e-3 --wd 1e-3 --bs 30 --lrScheduler --decoupledWD --wandb --temperature 2

