python ../parcellation/parcellation_utils.py -s 01 -d movie10
python ../parcellation/parcellation_utils.py -s 01 -d friends 
python ../parcellation/parcellation_utils.py -s 02 -d movie10
python ../parcellation/parcellation_utils.py -s 02 -d friends
python ../parcellation/parcellation_utils.py -s 03 -d movie10
python ../parcellation/parcellation_utils.py -s 03 -d friends
python ../parcellation/parcellation_utils.py -s 04 -d movie10
python ../parcellation/parcellation_utils.py -s 04 -d friends
python ../parcellation/parcellation_utils.py -s 05 -d movie10
python ../parcellation/parcellation_utils.py -s 05 -d friends
python ../parcellation/parcellation_utils.py -s 06 -d movie10
python ../parcellation/parcellation_utils.py -s 06 -d friends
